spring:
  application:
    name: medicine-online-manager-backend
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher #解决
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: medicine.online.backend.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: true # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8081
  servlet:
    context-path: /medicine-online-manager

logging:
  config: classpath:log/logback-spring.xml

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: medicine.online.backend.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true    #开启密码模式
    username: admin   #用户名
    password: 123456  #密码

auth:
  ignore_urls:
    - /sys/auth/login
    - /sys/auth/captcha
    - /actuator/**
    - /v3/api-docs/**
    - /webjars/**
    - /swagger/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /swagger-ui/**
    - /doc.html
    - /
    - /common/**

aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-nanjing.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5tR6Skw7tLwxn5N6jvaR
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: ###
    # oss的存储空间
    bucketName: karmel